export const data = [
  {
    id: 234,
    title: "movie",
    code: "https://github.com/Mohmed932/noTflix",
    visit: "https://no-tflix.vercel.app/",
    desc: "watch the toprated And poular move made with tmdb",
  },
  {
    id: 278,
    title: "Temp Mail",
    code: "https://github.com/Mohmed932/temp-mail",
    visit: "https://temp-mail-gamma.vercel.app/",
    desc: "temp mail for any website need to sign up",
  },
  {
    id: 218,
    title: "Quiz App",
    code: "https://github.com/Mohmed932/Quiz-App",
    visit: "https://quiz-app-two-hazel.vercel.app/",
    desc: "Quiz for front end devoloper",
  },
  {
    id: 478,
    title: "X-O game",
    code: "https://github.com/Mohmed932/-x-o-with-react-js",
    visit: "https://x-o-with-react-js.vercel.app/",
    desc: "X-O game by reactjs",
  },
  {
    id: 288,
    title: "translate",
    code: "https://github.com/Mohmed932/translate",
    visit: "https://translate-theta.vercel.app/",
    desc: "translate form any language to any language",
  },
  {
    id: 978,
    title: "Short Url",
    code: "https://github.com/Mohmed932/Url-short",
    visit: "https://url-short-sandy.vercel.app/",
    desc: "SHoRT cut Url",
  },
  {
    id: 0,
    title: "Code blog",
    code: "https://github.com/Mohmed932/project-Code-blog-",
    visit: "https://project-code-blog.vercel.app/",
    desc: "Add your notes and a picture on it using FileReader and database json-server",
  },
  {
    id: 1,
    title: "bazar",
    code: "https://github.com/Mohmed932/bazar",
    visit: "https://bazar-iota.vercel.app",
    desc: "A store that determines the prices of phones",
  },
  {
    id: 2,
    title: "الۡقُرۡآنۡ",
    code: "https://github.com/Mohmed932/Quran",
    visit: "https://quran-self.vercel.app",
    desc: "الۡقُرۡآنۡ، ويُسَمَّىٰ تكريمًا ٱلۡقُرۡآنُ ٱلۡكَرِيمُ، هو كتاب الله المعجز عند المسلمين،",
  },
  {
    id: 3,
    title: "Resto",
    code: "https://github.com/Mohmed932/-Resto",
    visit: "https://resto-one.vercel.app/",
    desc: "Restaurant to know the prices of sweets and their details",
  },
  {
    id: 4,
    title: "login",
    code: "https://github.com/Mohmed932/login",
    visit: "https://login-chi-cyan.vercel.app",
    desc: " Create Login Page",
  },
];
